server.port=8080
esper.window.config.dir=config/windows
spring.jackson.serialization.indent-output=true
logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web.socket=DEBUG
logging.level.com.example.esper=DEBUG
